<?php
/** @var \Module\Foundation\HttpSapi\ViewModelRenderer $this */
?>
<section id="main-slider" class="no-margin">
    <div class="carousel slide wet-asphalt">
        <div class="carousel-inner">
            <div class="item active" style="background-image: url(<?php echo $this->path('app-assets') ?>/images/slider/bg1.jpg)">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="carousel-content center centered">
                                <h2 class="boxed animation animated-item-1">Experience Rapid Application Framework</h2>
                                <h4 class="animation animated-item-2">Poirot, The Service Oriented, EventDriven PHP Experimental Framewrok.</h4>
                                <br>
                                <a class="btn btn-lg animation animated-item-3" target="_blank" href="https://github.com/phPoirot">Github</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<?php echo $section_features; ?>

<?php if ($events) { ?>
<section id="testimonial" class="alizarin">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="center">
                    <h2>Latest Contribution activity</h2>
                </div>
                <div class="gap"></div>
                <div class="row">
                    <?php foreach ($events as $event) { ?>
                    <?php $cycle = $this->cycle('<div class="col-md-4"> <!-- START -->', [1, 3]) ?>
                        <blockquote>
                            <p><strong><?php echo $event->repo->name; ?>:</strong> <?php echo $event->payload->message; ?></p>
                            <small><?php echo $event->payload->author->name ?> - <?php echo $event->created_at; ?></small>
                        </blockquote>
                    <?php $cycle = $this->cycle('</div> <!-- END -->', [$cycle, 3]) ?>
                    <?php } ?>
                    <?php if ($cycle->getCounter() !== 3) { ?>
                        </div> <!-- END -->
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
</section>
<?php } ?>
