<section id="services" class="emerald">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-6">
                <div class="media">
                    <div class="pull-left">
                        <i class="icon-code icon-md"></i>
                    </div>
                    <div class="media-body">
                        <h3 class="media-heading">Simplicity</h3>
                        <p>Easy to adapt the framework to your needs. It is explicitly designed to work efficiently as API Server.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6">
                <div class="media">
                    <div class="pull-left">
                        <i class="icon-repeat icon-md"></i>
                    </div>
                    <div class="media-body">
                        <h3 class="media-heading">Reusability</h3>
                        <p>Building blocks that can be used piece by piece with other applications or frameworks.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6">
                <div class="media">
                    <div class="pull-left">
                        <i class="icon-adjust icon-md"></i>
                    </div>
                    <div class="media-body">
                        <h3 class="media-heading">Enterprise</h3>
                        <p>Extensible, Engineered with performance tuning in mind and Very short learning curve.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
