<!DOCTYPE html>
<html lang="en">
<head>
    <?php echo $this->capture('inc.header.phtml') ?>
</head>
<body>
<header class="navbar navbar-inverse navbar-fixed-top wet-asphalt" role="banner">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo \Module\HttpFoundation\Actions::url('main/home') ?>">
<!--                <img src="--><?php //echo \Module\Foundation\Actions::path('www-assets') ?><!--/images/logo.png" alt="logo">-->
                <h4>Application Platform</h4>
            </a>
        </div>

        <?php echo $this->capture('inc.navigation-menu.phtml') ?>

    </div>
</header><!--/header-->

<?php echo $content; ?>

<?php // echo $this->capture('inc.decorate-content.phtml') ?>

<?php echo $this->capture('inc.footer.phtml') ?>
</body>
</html>
