<?php
/** @var \Poirot\Application\Sapi\Server\Http\Service\ViewModelRenderer $this */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php echo $this->capture('inc.header.phtml') ?>
</head><!--/head-->
<body>
<header class="navbar navbar-inverse navbar-fixed-top wet-asphalt" role="banner">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="index.html"><img src="<?php echo $this->path('app-assets') ?>/images/logo.png" alt="logo"></a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li class="active"><a href="<?php echo $this->url('site/home') ?>">Home</a></li>
                <li><a href="about-us.html">About Us</a></li>
                <li><a href="services.html">Services</a></li>
                <li><a href="portfolio.html">Portfolio</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Pages <i class="icon-angle-down"></i></a>
                    <ul class="dropdown-menu">
                        <li><a href="career.html">Career</a></li>
                        <li><a href="blog-item.html">Blog Single</a></li>
                        <li><a href="pricing.html">Pricing</a></li>
                        <li><a href="404.html">404</a></li>
                        <li><a href="registration.html">Registration</a></li>
                        <li class="divider"></li>
                        <li><a href="privacy.html">Privacy Policy</a></li>
                        <li><a href="terms.html">Terms of Use</a></li>
                    </ul>
                </li>
                <li><a href="blog.html">Blog</a></li>
                <li><a href="contact-us.html">Contact</a></li>
            </ul>
        </div>
    </div>
</header><!--/header-->

<?php echo $content; ?>

<footer id="footer" class="midnight-blue">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                &copy; 2013 <a target="_blank" href="http://shapebootstrap.net/" title="Free Twitter Bootstrap WordPress Themes and HTML templates">ShapeBootstrap</a>. All Rights Reserved.
            </div>
            <div class="col-sm-6">
                <ul class="pull-right">
                    <li><a href="#">Home</a></li>
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">Faq</a></li>
                    <li><a href="#">Contact Us</a></li>
                    <li><a id="gototop" class="gototop" href="#"><i class="icon-chevron-up"></i></a></li><!--#gototop-->
                </ul>
            </div>
        </div>
    </div>
</footer><!--/#footer-->

<script src="<?php echo $this->path('app-assets') ?>/js/jquery.js"></script>
<script src="<?php echo $this->path() ?>/js/bootstrap.min.js"></script>
<script src="<?php echo $this->path() ?>/js/jquery.prettyPhoto.js"></script>
<script src="<?php echo $this->path() ?>/js/main.js"></script>
</body>
</html>



<?php return ; ?>



















<html>



<body>
<a href="<?php echo $this->action()->url('site/pages/page', ['request_page'=>'about'])?>">About</a>
<a href="<?php echo $this->action()->url('site/pages/page', ['request_page'=>'contact'])?>">Contact</a>
<a href="<?php echo $this->action()->url('site/auth')?>">Register</a>
<hr/>

<?php echo $this->capture('inc.decorate-content.phtml') ?>

<?php echo $this->capture('inc.footer.phtml') ?>
</body>

</html>
