<footer id="footer" class="midnight-blue">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                &copy; <?php echo date('Y') ?> <a target="_blank" href="https://github.com/phPoirot/" title="">Poirot Framework</a>. under MIT Licence.
            </div>
            <div class="col-sm-6">
                <ul class="pull-right">
                    <li><a href="<?php // echo \Module\HttpFoundation\Actions::url('main/home') ?>">Home</a></li>
                    <li><a id="gototop" class="gototop" href="#"><i class="icon-chevron-up"></i></a></li><!--#gototop-->
                </ul>
            </div>
        </div>
    </div>
</footer>

<script src="<?php echo \Module\Foundation\Actions::path('www-assets') ?>/js/jquery.js"></script>
<script src="<?php echo \Module\Foundation\Actions::path('www-assets') ?>/js/bootstrap.min.js"></script>
<script src="<?php echo \Module\Foundation\Actions::path('www-assets') ?>/js/main.js"></script>
