<div class="collapse navbar-collapse">
    <ul class="nav navbar-nav navbar-right">
        <li><a href="<?php echo $this->url('site/home') ?>">Home</a></li>
        <!--<li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Pages <i class="icon-angle-down"></i></a>
            <ul class="dropdown-menu">
                <li><a href="404.html">404</a></li>
                <li class="divider"></li>
            </ul>
        </li>-->
    </ul>
</div>