<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">
<title>Poirot Framework</title>

<?php $this->path('app-assets') ## set app-assets as last invoked path and continue ...  ?>

<link href="<?php echo $this->path() ?>/css/bootstrap.min.css" rel="stylesheet">
<link href="<?php echo $this->path() ?>/css/font-awesome.min.css" rel="stylesheet">
<link href="<?php echo $this->path() ?>/css/prettyPhoto.css" rel="stylesheet">
<link href="<?php echo $this->path() ?>/css/animate.css" rel="stylesheet">
<link href="<?php echo $this->path() ?>/css/main.css" rel="stylesheet">
<!--[if lt IE 9]>
<script src="<?php echo $this->path() ?>/js/html5shiv.js"></script>
<script src="<?php echo $this->path() ?>/js/respond.min.js"></script>
<![endif]-->
<link rel="shortcut icon" href="<?php echo $this->path() ?>/images/ico/favicon.ico">
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="<?php echo $this->path() ?>/images/ico/apple-touch-icon-144-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?php echo $this->path() ?>/images/ico/apple-touch-icon-114-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?php echo $this->path() ?>/images/ico/apple-touch-icon-72-precomposed.png">
<link rel="apple-touch-icon-precomposed" href="<?php echo $this->path() ?>/images/ico/apple-touch-icon-57-precomposed.png">
