<?php
/** @var \Application\HttpSapi\ViewModelRenderer $this */
?>
<section id="main-slider" class="no-margin">
    <div class="carousel slide wet-asphalt">
        <div class="carousel-inner">
            <div class="item active" style="background-image: url(<?php echo $this->path('app-assets') ?>/images/slider/bg1.jpg)">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="carousel-content center centered">
                                <h2 class="boxed animation animated-item-1">Experience Rapid Application Framework</h2>
                                <h4 class="animation animated-item-2">Poirot, The Service Oriented, EventDriven PHP Experimental Framewrok.</h4>
                                <br>
                                <a class="btn btn-lg animation animated-item-3" target="_blank" href="https://github.com/phPoirot">Github</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section id="services" class="emerald">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-6">
                <div class="media">
                    <div class="pull-left">
                        <i class="icon-code icon-md"></i>
                    </div>
                    <div class="media-body">
                        <h3 class="media-heading">Simplicity</h3>
                        <p>Easy to adapt the framework to your needs. It is explicitly designed to work efficiently as API Server.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6">
                <div class="media">
                    <div class="pull-left">
                        <i class="icon-repeat icon-md"></i>
                    </div>
                    <div class="media-body">
                        <h3 class="media-heading">Reusability</h3>
                        <p>Building blocks that can be used piece by piece with other applications or frameworks.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6">
                <div class="media">
                    <div class="pull-left">
                        <i class="icon-adjust icon-md"></i>
                    </div>
                    <div class="media-body">
                        <h3 class="media-heading">Enterprise</h3>
                        <p>Extensible, Engineered with performance tuning in mind and Very short learning curve.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<?php if ($events) { ?>
<section id="testimonial" class="alizarin">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="center">
                    <h2>Latest Contribution activity</h2>
                </div>
                <div class="gap"></div>
                <div class="row">
                    <?php foreach ($events as $event) { ?>
                    <div class="col-md-4">
                        <blockquote>
                            <p><strong><?php echo $event->repo->name; ?>:</strong> <?php echo $event->payload->message; ?></p>
                            <small><?php echo $event->payload->author->name ?> - <?php echo $event->created_at; ?></small>
                        </blockquote>
                    </div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
</section>
<?php } ?>
