<section id="error" class="container">
    <h1>Something is wrong !!</h1>
    <p><?php echo $exception->getMessage() ?></p>
    <a class="btn btn-success" href="<?php echo $this->url('main/home') ?>">GO BACK TO THE HOMEPAGE</a>
</section>

<section class="container">
<?php if (isset($display_exceptions) && $display_exceptions): ?>

    <?php if(isset($exception) && $exception instanceof \Exception): ?>
        <hr/>
        <h2>Additional information:</h2>
        <h3><?php echo get_class($exception); ?></h3>
        <dl>
            <dt>File:</dt>
            <dd>
                <pre class="prettyprint linenums"><?php echo $exception->getFile() ?>:<?php echo $exception->getLine() ?></pre>
            </dd>
            <dt>Message:</dt>
            <dd>
                <pre class="prettyprint linenums"><?php echo $exception->getMessage() ?></pre>
            </dd>
            <dt>Stack trace:</dt>
            <dd>
                <pre class="prettyprint linenums"><?php echo $exception->getTraceAsString() ?></pre>
            </dd>
        </dl>
        <?php
        $e = $exception->getPrevious();
        if ($e) :
            ?>
            <hr/>
            <h2>Previous exceptions:</h2>
            <ul class="unstyled">
                <?php while($e) : ?>
                    <li>
                        <h3><?php echo get_class($e); ?></h3>
                        <dl>
                            <dt>File:</dt>
                            <dd>
                                <pre class="prettyprint linenums"><?php echo $e->getFile() ?>:<?php echo $e->getLine() ?></pre>
                            </dd>
                            <dt>Message:</dt>
                            <dd>
                                <pre class="prettyprint linenums"><?php echo $e->getMessage() ?></pre>
                            </dd>
                            <dt>Stack trace:</dt>
                            <dd>
                                <pre class="prettyprint linenums"><?php echo $e->getTraceAsString() ?></pre>
                            </dd>
                        </dl>
                    </li>
                    <?php
                    $e = $e->getPrevious();
                endwhile;
                ?>
            </ul>
        <?php endif; ?>

    <?php else: ?>

        <h3>No Exception available></h3>

    <?php endif ?>

<?php endif ?>
</section>
